### ISSUE TITLE
Reproducing Evaluation Results

### ISSUE THREAD

**Issue by greeneggsandyaml** [yzxing87/pytorch-deep-video-prior#1]
Hello authors, thank you for your great work!

I am writing a blog post about your work and I was interested in reproducing the results completely (on DAVIS/the Bonneel dataset). Would it be possible for you to provide evaluation code or instructions as to evaluating `E_warp` and `F_data` for your method on these datasets? 

All the best,

**Comment by yzxing87** [comment]
Hi, thanks for your interest!

To evaluate E_warp, you need to install PWC-Net to calculate optical flow. Please follow the instruction [here](https://github.com/ChenyangLEI/deep-video-prior/issues/4#issuecomment-730376178). F_data is actually measured by PSNR, which is easy to implement. 

```python
def compute_psnr(img1, img2):
    mse = np.mean( (img1 - img2) ** 2 )
    if mse == 0:
        return 100
    PIXEL_MAX = 1.
    return 20 * math.log10(PIXEL_MAX / math.sqrt(mse))
```

We are preparing all our results and will make them public online for evaluation and further comparisons.

**Comment by greeneggsandyaml** [comment]
Hi, thank you for your response! I really appreciate it. I will work to reproduce the results and keep you updated. When I finish reproducing, I will close this issue :)
