### ISSUE TITLE
CUDA out of memory

### ISSUE THREAD

**Issue by myname1111** [yzxing87/pytorch-deep-video-prior#4]
When attempting to run main_IRT.py with 6000 frames causes RuntimeError: CUDA out of memory. This could be fixed by reducing batch size or use memory when needed. Also, I`m using google Colab and yes the ram that google collab had offered did not reach the full amount of ram instead, it stopped at 2/3 of it and caused this error

> Traceback (most recent call last):
  File "main_IRT.py", line 139, in <module>
 net_in = torch.from_numpy(net_in).permute(0,3,1,2).float().to(device)
RuntimeError: CUDA out of memory. Tried to allocate 20.00 MiB (GPU 0; 14.73 GiB total capacity; 12.13 GiB already allocated; 5.88 MiB free; 13.79 GiB reserved in total by PyTorch)

**Comment by yzxing87** [comment]
Hi, the error may be caused by loading all the 6000 frames into the memory. Previously we did this for accelarating training process. You can also load the frame just before each iteration. I think torch.utils.data.DataLoader can be a better option for this issue. We will update the code using pytorch dataloader. Thx.

**Comment by SolomGfxcolor** [comment]
> When attempting to run main_IRT.py with 6000 frames causes RuntimeError: CUDA out of memory. This could be fixed by reducing batch size or use memory when needed. Also, I`m using google Colab and yes the ram that google collab had offered did not reach the full amount of ram instead, it stopped at 2/3 of it and caused this error
> 
> > Traceback (most recent call last):
> > File "main_IRT.py", line 139, in 
> > net_in = torch.from_numpy(net_in).permute(0,3,1,2).float().to(device)
> > RuntimeError: CUDA out of memory. Tried to allocate 20.00 MiB (GPU 0; 14.73 GiB total capacity; 12.13 GiB already allocated; 5.88 MiB free; 13.79 GiB reserved in total by PyTorch)

Can you send a colab notebook to me please 🙏🏻 
My Email :- eslam.alfnnan15@gmail.com

**Comment by semel1** [comment]
"You can also load the frame just before each iteration. I think torch.utils.data.DataLoader can be a better option for this issue. We will update the code using pytorch dataloader." Any update? 
Could you please provide me with more detail on how to " load the frame just before each iteration"
