### ISSUE TITLE
copy of another issue

### ISSUE THREAD

**Issue by myname1111** [yzxing87/pytorch-deep-video-prior#5]
When attempting to run main_IRT.py with 6000 frames causes RuntimeError: CUDA out of memory. This could be fixed by reducing batch size or use memory when needed. Also, I`m using google Colab and yes the ram that google collab had offered did not reach the full amount of ram instead, it stopped at 2/3 of it and caused this error

> Traceback (most recent call last):
  File "main_IRT.py", line 139, in <module>
 net_in = torch.from_numpy(net_in).permute(0,3,1,2).float().to(device)
RuntimeError: CUDA out of memory. Tried to allocate 20.00 MiB (GPU 0; 14.73 GiB total capacity; 12.13 GiB already allocated; 5.88 MiB free; 13.79 GiB reserved in total by PyTorch)

**Comment by yzxing87** [comment]
Please note this is the same issue as [this one](https://github.com/yzxing87/pytorch-deep-video-prior/issues/4).

**Comment by myname1111** [comment]
don't know how to delete an issue so ill just close this one sorry. I thought I hadn't posted it yet(since you already closed it). sorry for the inconvenience
