### ISSUE TITLE
Temporally-consistent version of depth estimation

### ISSUE THREAD

**Issue by semel1** [yzxing87/pytorch-deep-video-prior#7]
Is it possible to generate temporally consistent video from depth map sequence obtained by depth estimation (MIDAS) similar to "Blind Video Temporal Consistency project" https://github.com/lulu1315/BlindConsistency or https://github.com/nbonneel/blindconsistency?

**Comment by ChenyangLEI** [comment]
Yes, it is possible.

**Comment by semel1** [comment]
Thanks for your kind reply.
 Is using "model colorization" with 50 epoch the proper way to go? (input - original color video, processed - depth estimation)

**Comment by yzxing87** [comment]
You can try 'model colorization' or 'model dehazing'. Since IRT may not be necessary for your task.

**Comment by semel1** [comment]
Great, thanks again. I'll try as soon as I get my GPU (currently I'm trying to test using CPU only, but it is way too slow)
