### ISSUE TITLE
CUDA out of memory

### ISSUE THREAD

**Issue by semel1** [yzxing87/pytorch-deep-video-prior#8]
I noticed that a similar issue has been closed. 
However, I have the same problem.
So, "You can also load the frame just before each iteration. I think torch.utils.data.DataLoader can be a better option for this issue. We will update the code using pytorch dataloader."
Any code update?
Could you please provide me with more detail on how to " load the frame just before each iteration"

**Comment by yzxing87** [comment]
Hi, I mean, in line 136-141 of main_IRT.py, we load the whole video into memory for accelerating training. You can also load the data just before each iteration, by changing line 162 and line 168.
